### ISSUE TITLE
Plugin crashes after loading

### ISSUE THREAD

**Issue by Crawcik** [chicken-with-lips/flax-plugin-ue4-utilities#1]
If someone doesnt have C++ tools for flax installed it crashes
This is because in `UE4ContentImporterEditor.Build.cs` **BuildNativeCode** should be set in **Init** method, not in **Setup**
```cs
    /// <inheritdoc />
    public override void Init()
    {
        base.Init();

        // C#-only scripting
        BuildNativeCode = false;
    }
```

**Comment by iainmckay** [comment]
That's interesting as I started this plugin using the official ExamplePlugin. I've made this change blind as I don't currently have an environment without C++ tooling. It doesn't appear to negatively affect my environment however.

**Comment by iainmckay** [comment]
Thanks again for the report.
